default:
  base:
    image: "{{image_fullname}}"
    env:
      ENV_FOR_DYNACONF: "{{env_name}}"
    volumes: >-
      {{"[folder+':'+folder for folder in list(dirs_info.values())+[project_folder]]"|
      eval(dirs_info=settings.PROJECT.dirs,project_folder=project_folder)}}
    working_dir: "{{project_folder}}"
    state: present