- hosts: all
  roles:
    - name: base
  tasks:
    - include_tasks: { file: 'service_tasks/service.yaml' }
      vars: { service_options: "{{item}}" }
      loop:
        #        - name: crop_field_segmentation
        #          command: python -m app.pipeline

        - name: salem_worker
          celery_worker:
            queues: crop_field_segmentation_salem

        - name: job_runner
          celery_worker:
            queues: job_runner
            concurrency: 5

        - name: crop_segmentation_tester
          command: python -m app.tester




    - name: Greetings!!!
      debug:
        msg: "Deployment successfull!!!"
