- hosts: all
  roles:
    - name: base
  vars:
#    show_container_details: yes
#    launch_container: no
  tasks:
    - include_role: { name: base, tasks_from: infrastructure.yaml }

    # --no-postgres-port
    # --no-ui-port
    # --no-server-port
    #    - debug:
    #        msg: >-
    #          {{
    #          "prefect backend server;
    #          screen -XS prefect_server quit;
    #          screen -mdS prefect_server
    #          prefect server start
    #          --postgres-port {postgres}
    #          --hasura-port {hasura}
    #          --graphql-port {graphql}
    #          --ui-port {ui}
    #          --server-port {server}
    #          --no-hasura-port
    #          --no-graphql-port
    #          --use-volume;"|
    #          fmt(infra.PREFECT.ports)
    #          }}
    #      screen -XS prefect_server quit;

#    - name: Run prefect
#      raw: >-
#        {{
#        "prefect backend server;
#        screen -mdS prefect_server
#        prefect server start
#        --postgres-port {postgres}
#        --hasura-port {hasura}
#        --graphql-port {graphql}
#        --ui-port {ui}
#        --server-port {server}
#        --no-hasura-port
#        --no-graphql-port
#        --use-volume;"|
#        fmt(infra.PREFECT.ports)
#        }}