version: "3"
services:
  crop_field_segmentation:
    image: "hub.egistic.kz/meteo:latest"
    restart: "always"
    volumes:
      - ".:/usr/src/app"
    networks:
      - "redis_network"
    command: bash -c "celery -A celery_worker worker -Q crop_field_segmentation -P threads --loglevel=INFO"

networks:
  redis_network:
    external:
      name: "django"