version: "3"
services:
  crop_field_segmentation:
    image: "hub.egistic.kz/crop_field_segmentation:latest"
    restart: "always"
    volumes:
      - ".:/usr/src/app"
      - "/nfs/storage/data/Crop_Field_Segmentation/caches:/usr/src/app/caches"
      - "/nfs/storage/data/Crop_Field_Segmentation/data:/usr/src/app/data"
      - "/mnt/efs/fs1/caches/imagiflow/individual_bands:/usr/src/app/temp"
    networks:
      - "redis_network"
    command: bash -c "celery -A celery_worker worker -Q crop_field_segmentation -P threads --loglevel=INFO"

networks:
  redis_network:
    external:
      name: "django"