- name: 'Create project networks'
  docker_network:
    name: "{{item.name}}"
  loop: "{{docker.infra.networks|default([])}}"

- include_tasks: process_docker_info.yaml
  vars:
    config_name: infrastructure_services
    merge_items: [ "{{docker.infra}}" ]
    merge_items_first: yes

