- name: Generate ansible secret
  include_tasks:
    file: "initial/generate_ansible_secret.yaml"
    apply: { tags: [ 'init_vault','init' ] }
  tags: [ 'init_vault','init' ]
  when: ansible_connection=='local'

- include_tasks: initial/pull_project.yaml
  when: ansible_connection!='local'

- name: Install provision dependencies
  pip:
    requirements: "{{project_folder}}/provision/roles/base/files/.requirements.txt"
  tags: [ 'install_deps','init' ]

- include_tasks: initial/extract_project_info.yaml
- include_tasks: initial/generate_settings.yaml
- include_tasks: generate_project_tasks.yaml

- name: Build docker image
  shell: "{{project_tasks.docker_build}}"
  when: build_docker_image

