- set_fact:
    rci:
      show_container_details: "{{show_container_details|default(False)}}"
      launch_container: "{{launch_container|default(True)}}"
- name: Generate docker container info
  eval:
    expression: |
      container_data = Box(info)

      def update(key, info_default=None, kwargs=None):
          if kwargs:
              kwargs.update(info.get(key, info_default))
              container_data.update({key: kwargs})
          elif (key in info) or info_default:
              container_data.update({key: info.get(key, info_default)})

      container_data.image = info['image']
      update('name', container_data.image.split(':')[0])
      update('hostname', container_data.name)

      env = Box()
      env.TZ = 'Asia/Almaty'
      update('env', {}, env)

      update('comparisons', {}, {'*': 'strict'})
      update('volumes', [])

      var_name="{{var_name|default('')}}" or container_data.name
    #      infra.update({var_name:dict(info=container_data,meta=meta)})
    data:
      #      infra: "{{infra|default({})}}"
      meta: "{{meta|default({})}}"
      info:
        image: "{{info.image}}"
        name: "{{info.name|default(omit)}}"
        hostname: "{{info.hostname|default(omit)}}"
        command: "{{info.command|default(omit)}}"
        volumes: "{{info.volumes|default(omit)}}"
        env: "{{info.env|default(omit)}}"
        env_file: "{{info.env_file|default(omit)}}"
        ports: "{{info.ports|default(omit)}}"
        exposed_ports: "{{info.exposed_ports|default(omit)}}"
        exposed: "{{info.exposed|default(omit)}}"
        expose: "{{info.expose|default(omit)}}"
        networks: "{{info.networks|default(omit)}}"
        user: "{{info.user|default(omit)}}"
        working_dir: "{{info.working_dir|default(omit)}}"
        healthcheck: "{{info.healthcheck|default(omit)}}"
        sysctls: "{{info.sysctls|default(omit)}}"
        mounts: "{{info.mounts|default(omit)}}"
        networks_cli_compatible: "{{info.networks_cli_compatible|default(False)}}"
        comparisons: "{{info.comparisons|default(omit)}}"
        pull: "{{info.pull|default(omit)}}"
        restart: "{{info.restart|default(omit)}}"
        restart_policy: "{{info.restart_policy|default(omit)}}"
        recreate: "{{info.recreate|default(omit)}}"
        state: "{{info.state|default(omit)}}"
    out:
      - container_data
  #      - infra
  register: eval_meta
#- set_fact:
#    infra: "{{eval_meta.infra}}"
- debug: msg="Running {{eval_meta.container_data.name}}"
- debug: msg="{{eval_meta.container_data}}"
  when: rci.show_container_details
- name: Launch container
  docker_container: "{{eval_meta.container_data}}"
  when: rci.launch_container