default:
  PROJECT:
    wkt_geom: "Polygon ((29.07090781880005181 37.57396591446815393, 141.57053978732929522 37.57396591446815393, 141.57053978732929522 70.01110538979037301, 29.07090781880005181 70.01110538979037301, 29.07090781880005181 37.57396591446815393))"
  CELERY:
    task_base_name: "yield_pred"
    config:
      imports: [ 'app.celery_tasks' ]
      result_persistent: False
      task_acks_late: False
      task_acks_on_failure_or_timeout: False
      task_track_started: True
      enable_utc: True
      timezone: "Asia/Almaty"
      acks_on_failure_or_timeout: False
      worker_send_task_events: True
      task_send_sent_event: True
      task_inherit_parent_priority: True
      worker_prefetch_multiplier: 1
      worker_concurrency: 1
      worker_max_tasks_per_child: 100
      task_queue_max_priority: 10
      task_default_priority: 5
      task_create_missing_queues: True
      task_remote_tracebacks: True
      task_time_limit:
      task_soft_time_limit:
      task_ignore_result: False
      task_always_eager: False
      accept_content: [ 'json' ]
      result_accept_content: [ 'json' ]
      result_backend: &rb "{{'redis://{username}:{password}@{host}:{port}'|fmt(infra.REDIS)}}"
      broker_url: *rb
      task_serializer: 'json'
      result_serializer: 'json'
      broker_transport_options:
        visibility_timeout: 86400

development:
  PROJECT:
    dirs:
      #      dataset_folder: /home/lgblkb/Data/YieldPrediction
      s2_storage_folder: /home/lgblkb/PycharmProjects/imagination/sentinel2
      cache_folder: /home/lgblkb/caches/Crop_Field_Segmentation/
      data_folder: /home/lgblkb/data/Crop_Field_Segmentation/

staging:
  PROJECT:
    dirs:
      #      dataset_folder: /mnt/md0/Data/YieldPrediction
      s2_storage_folder: /mnt/md0/imagination_data/sentinel2
      cache_folder: /mnt/md0/caches/Crop_Field_Segmentation
      data_folder: /mnt/md0/data/Crop_Field_Segmentation/

production:
  PROJECT:
    dirs:
      s2_storage_folder: /nfs/storage/sat_images/sentinel2
      cache_folder: /home/egistic_db/caches/Crop_Field_Segmentation
      data_folder: /nfs/storage/data/Crop_Field_Segmentation/




