default:
  networks:
    - name: "{{poetry_info.name}}_network"
    - name: "devel_network"


production:
  networks:
    - name: "{{poetry_info.name}}_network"
    - name: 'redis_network'
    #    - name: 'memcached_network'
    - name: 'postgis'
