- name: Check vault secret existence
  stat:
    path: "{{vault_secret_path}}"
  register: secret_path_existence

- name: Generate ansible secret
  shell: |
    python3 -c "
    import os
    from secrets import choice
    import string

    password_length = 32
    alphabet = string.ascii_letters + string.digits
    password = ''.join(choice(alphabet) for i in range(password_length))

    filename = '{{secret_path}}'
    assert not os.path.exists(filename)
    with open(filename, 'w') as file:
        file.write(password)"
  when: not secret_path_existence.stat.exists